version: '3.8'

services:
  # Application service
  app:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/src/client/node_modules
    ports:
      - "5000:5000"  # Server API
      - "3000:3000"  # Client development server
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/litspark
      - JWT_SECRET=dev_jwt_secret
      - PORT=5000
    depends_on:
      - db
    command: npm run dev
    networks:
      - litspark-network

  # PostgreSQL Database
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=litspark
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - litspark-network

  # PgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@litspark.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - litspark-network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  litspark-network:
    driver: bridge
